CREATE TABLE IF NOT EXISTS game_genres (
 game_id INTEGER NOT NULL REFERENCES games ( id ) ON DELETE CASCADE,
 genre_id INTEGER NOT NULL REFERENCES genres ( id ) ON DELETE CASCADE,
 PRIMARY KEY ( game_id, genre_id )
);
